---
apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    name: server
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
  containers:
    - name: server
      image: docker.io/piotr439/https-proxy:dev_2
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort 
  selector:
    name: server
  ports:
    - name: https
      protocol: TCP
      port: 443 
      targetPort: 3000
      nodePort: 30001 

